### ISSUE TITLE
Streamer_UpdateEx last parameter missing.

### ISSUE THREAD

**Issue by lleps** [Shoebill/streamer-wrapper#5]
Hi. In one of the latest versions of streamer plugin, a new parameter "compensatedtime" was added to Streamer_UpdateEx: https://github.com/samp-incognito/samp-streamer-plugin/commit/f6eaa87a65b2b9198f9bfc7d0669eee7562838ea

The problem is that this plugin does not contains it.

**Comment by 123marvin123** [comment]
Fixed in 166303ace4199cba43732b4810eb6ef259bf3df7
