### ISSUE TITLE
Using maps created with pawn

### ISSUE THREAD

**Issue by damafo** [Shoebill/streamer-wrapper#7]
I have some maps with streamer codes, but they're created with pawn code. Can i just add them as a filterscript?

**Comment by 123marvin123** [comment]
No, you will have to convert them. I believe there are some converters available. 

I will try to find one for you.

**Comment by 123marvin123** [comment]
It looks like there are none available right now. You have to convert them manually

**Comment by damafo** [comment]
I found a site. You can give custom formats to it for converting. Can you help to write the custom format for DynamicObject and Vehicle ?

https://convertffs.com/
